import axios from 'axios';
import { StreamingProviderInfo, WatchmodeSource } from '../types/index.js';
import prisma from './prisma.js';

const WATCHMODE_BASE_URL = 'https://api.watchmode.com/v1';

// Catalog of known popular show providers and fallback mappings
const POPULAR_SHOW_PROVIDERS: Record<string, StreamingProviderInfo[]> = {
  severance: [
    { providerName: 'Apple TV+', logoUrl: 'https://images.watchmode.com/provider_logos/371_autogenerated.png', deepLink: 'https://tv.apple.com/us/show/severance/umc.cmc.1srk2goyh2q2zpqvq6xwnqnxq', type: 'sub', region: 'US' },
  ],
  'house of the dragon': [
    { providerName: 'Max', logoUrl: 'https://images.watchmode.com/provider_logos/387_autogenerated.png', deepLink: 'https://play.max.com', type: 'sub', region: 'US' },
  ],
  'the last of us': [
    { providerName: 'Max', logoUrl: 'https://images.watchmode.com/provider_logos/387_autogenerated.png', deepLink: 'https://play.max.com', type: 'sub', region: 'US' },
  ],
  'stranger things': [
    { providerName: 'Netflix', logoUrl: 'https://images.watchmode.com/provider_logos/203_autogenerated.png', deepLink: 'https://www.netflix.com', type: 'sub', region: 'US' },
  ],
  'the bear': [
    { providerName: 'Hulu', logoUrl: 'https://images.watchmode.com/provider_logos/157_autogenerated.png', deepLink: 'https://www.hulu.com', type: 'sub', region: 'US' },
    { providerName: 'Disney+', logoUrl: 'https://images.watchmode.com/provider_logos/372_autogenerated.png', deepLink: 'https://www.disneyplus.com', type: 'sub', region: 'US' },
  ],
  'the boys': [
    { providerName: 'Prime Video', logoUrl: 'https://images.watchmode.com/provider_logos/26_autogenerated.png', deepLink: 'https://www.amazon.com/primevideo', type: 'sub', region: 'US' },
  ],
  fallout: [
    { providerName: 'Prime Video', logoUrl: 'https://images.watchmode.com/provider_logos/26_autogenerated.png', deepLink: 'https://www.amazon.com/primevideo', type: 'sub', region: 'US' },
  ],
  shogun: [
    { providerName: 'Hulu', logoUrl: 'https://images.watchmode.com/provider_logos/157_autogenerated.png', deepLink: 'https://www.hulu.com', type: 'sub', region: 'US' },
    { providerName: 'Disney+', logoUrl: 'https://images.watchmode.com/provider_logos/372_autogenerated.png', deepLink: 'https://www.disneyplus.com', type: 'sub', region: 'US' },
  ],
  'the mandalorian': [
    { providerName: 'Disney+', logoUrl: 'https://images.watchmode.com/provider_logos/372_autogenerated.png', deepLink: 'https://www.disneyplus.com', type: 'sub', region: 'US' },
  ],
  'ted lasso': [
    { providerName: 'Apple TV+', logoUrl: 'https://images.watchmode.com/provider_logos/371_autogenerated.png', deepLink: 'https://tv.apple.com', type: 'sub', region: 'US' },
  ],
  'yellowstone': [
    { providerName: 'Peacock', logoUrl: 'https://images.watchmode.com/provider_logos/389_autogenerated.png', deepLink: 'https://www.peacocktv.com', type: 'sub', region: 'US' },
    { providerName: 'Paramount+', logoUrl: 'https://images.watchmode.com/provider_logos/444_autogenerated.png', deepLink: 'https://www.paramountplus.com', type: 'sub', region: 'US' },
  ],
  'poker face': [
    { providerName: 'Peacock', logoUrl: 'https://images.watchmode.com/provider_logos/389_autogenerated.png', deepLink: 'https://www.peacocktv.com', type: 'sub', region: 'US' },
  ]
};

const NETWORK_TO_PROVIDER: Record<string, { providerName: string; logoUrl: string; deepLink: string }> = {
  'apple tv+': { providerName: 'Apple TV+', logoUrl: 'https://images.watchmode.com/provider_logos/371_autogenerated.png', deepLink: 'https://tv.apple.com' },
  'netflix': { providerName: 'Netflix', logoUrl: 'https://images.watchmode.com/provider_logos/203_autogenerated.png', deepLink: 'https://www.netflix.com' },
  'hbo': { providerName: 'Max', logoUrl: 'https://images.watchmode.com/provider_logos/387_autogenerated.png', deepLink: 'https://play.max.com' },
  'max': { providerName: 'Max', logoUrl: 'https://images.watchmode.com/provider_logos/387_autogenerated.png', deepLink: 'https://play.max.com' },
  'disney+': { providerName: 'Disney+', logoUrl: 'https://images.watchmode.com/provider_logos/372_autogenerated.png', deepLink: 'https://www.disneyplus.com' },
  'hulu': { providerName: 'Hulu', logoUrl: 'https://images.watchmode.com/provider_logos/157_autogenerated.png', deepLink: 'https://www.hulu.com' },
  'fx': { providerName: 'Hulu', logoUrl: 'https://images.watchmode.com/provider_logos/157_autogenerated.png', deepLink: 'https://www.hulu.com' },
  'fx on hulu': { providerName: 'Hulu', logoUrl: 'https://images.watchmode.com/provider_logos/157_autogenerated.png', deepLink: 'https://www.hulu.com' },
  'amazon': { providerName: 'Prime Video', logoUrl: 'https://images.watchmode.com/provider_logos/26_autogenerated.png', deepLink: 'https://www.amazon.com/primevideo' },
  'prime video': { providerName: 'Prime Video', logoUrl: 'https://images.watchmode.com/provider_logos/26_autogenerated.png', deepLink: 'https://www.amazon.com/primevideo' },
  'peacock': { providerName: 'Peacock', logoUrl: 'https://images.watchmode.com/provider_logos/389_autogenerated.png', deepLink: 'https://www.peacocktv.com' },
  'nbc': { providerName: 'Peacock', logoUrl: 'https://images.watchmode.com/provider_logos/389_autogenerated.png', deepLink: 'https://www.peacocktv.com' },
  'paramount+': { providerName: 'Paramount+', logoUrl: 'https://images.watchmode.com/provider_logos/444_autogenerated.png', deepLink: 'https://www.paramountplus.com' },
  'cbs': { providerName: 'Paramount+', logoUrl: 'https://images.watchmode.com/provider_logos/444_autogenerated.png', deepLink: 'https://www.paramountplus.com' },
  'amc': { providerName: 'AMC+', logoUrl: 'https://images.watchmode.com/provider_logos/373_autogenerated.png', deepLink: 'https://www.amcplus.com' },
  'amc+': { providerName: 'AMC+', logoUrl: 'https://images.watchmode.com/provider_logos/373_autogenerated.png', deepLink: 'https://www.amcplus.com' },
  'showtime': { providerName: 'Paramount+ with Showtime', logoUrl: 'https://images.watchmode.com/provider_logos/444_autogenerated.png', deepLink: 'https://www.paramountplus.com' },
  'starz': { providerName: 'Starz', logoUrl: 'https://images.watchmode.com/provider_logos/140_autogenerated.png', deepLink: 'https://www.starz.com' },
};

export class WatchmodeService {
  private apiKey: string | null = process.env.WATCHMODE_API_KEY || null;

  /**
   * Resolve streaming providers for a given show
   */
  async getStreamingProviders(
    title: string,
    network: string | null = null,
    region = 'US'
  ): Promise<StreamingProviderInfo[]> {
    // If API key is provided, try real Watchmode API call
    if (this.apiKey) {
      try {
        const providers = await this.fetchFromWatchmodeApi(title, region);
        if (providers.length > 0) return providers;
      } catch (err) {
        console.warn(`[WatchmodeService] API lookup failed for "${title}", falling back to heuristics:`, err);
      }
    }

    // Heuristic 1: Check known popular shows catalog
    const normalizedTitle = title.toLowerCase().trim();
    if (POPULAR_SHOW_PROVIDERS[normalizedTitle]) {
      return POPULAR_SHOW_PROVIDERS[normalizedTitle].map(p => ({ ...p, region }));
    }

    // Heuristic 2: Check matching network name
    if (network) {
      const normalizedNetwork = network.toLowerCase().trim();
      for (const [netKey, prov] of Object.entries(NETWORK_TO_PROVIDER)) {
        if (normalizedNetwork.includes(netKey) || netKey.includes(normalizedNetwork)) {
          return [
            {
              providerName: prov.providerName,
              logoUrl: prov.logoUrl,
              deepLink: prov.deepLink,
              type: 'sub',
              region,
            },
          ];
        }
      }
    }

    // Fallback default: General streaming / purchase option
    return [
      {
        providerName: 'Buy / Rent (Apple / Prime / Google)',
        logoUrl: 'https://images.watchmode.com/provider_logos/26_autogenerated.png',
        deepLink: `https://www.google.com/search?q=where+to+watch+${encodeURIComponent(title)}`,
        type: 'buy',
        region,
      },
    ];
  }

  /**
   * Real Watchmode API Integration
   */
  private async fetchFromWatchmodeApi(title: string, region: string): Promise<StreamingProviderInfo[]> {
    const searchRes = await axios.get(`${WATCHMODE_BASE_URL}/search/`, {
      params: {
        apiKey: this.apiKey,
        search_field: 'name',
        search_value: title,
        types: 'tv',
      },
      timeout: 5000,
    });

    const titleResults = searchRes.data?.title_results;
    if (!titleResults || titleResults.length === 0) {
      return [];
    }

    const titleId = titleResults[0].id;
    const sourcesRes = await axios.get<WatchmodeSource[]>(`${WATCHMODE_BASE_URL}/title/${titleId}/sources/`, {
      params: {
        apiKey: this.apiKey,
        regions: region,
      },
      timeout: 5000,
    });

    // Deduplicate and format sources
    const seen = new Set<string>();
    const providers: StreamingProviderInfo[] = [];

    for (const src of sourcesRes.data || []) {
      if (src.region === region && !seen.has(src.name)) {
        seen.add(src.name);
        providers.push({
          providerName: src.name,
          logoUrl: `https://images.watchmode.com/provider_logos/${src.source_id}_autogenerated.png`,
          deepLink: src.web_url || src.ios_url || src.android_url,
          type: src.type || 'sub',
          region: src.region,
        });
      }
    }

    return providers;
  }

  /**
   * Synchronize streaming providers for a show in PostgreSQL
   */
  async syncStreamingProvidersForShow(
    showId: string,
    title: string,
    network: string | null = null,
    region = 'US'
  ) {
    const providers = await this.getStreamingProviders(title, network, region);

    // Delete existing providers for this show & region to avoid stale duplicates
    await prisma.streamingProvider.deleteMany({
      where: { showId, region },
    });

    // Upsert fresh providers
    for (const p of providers) {
      await prisma.streamingProvider.create({
        data: {
          showId,
          providerName: p.providerName,
          logoUrl: p.logoUrl,
          deepLink: p.deepLink,
          type: p.type,
          region: p.region,
        },
      });
    }
  }
}

export const watchmodeService = new WatchmodeService();
export default watchmodeService;
